#!/bin/bash
# This script must be run in the application root directory

echo "Testing Power"
for host in `grep -v ^# test/test_host_list`
do
	echo "Testing $host"
	echo "Running Status:"
	./dlipower/dlipower.py --hostname $host
	echo "Testing power management commands, each line should show the same command on both sides of the : character"
	echo -n "Forcing power to OFF: "
	./dlipower/dlipower.py --hostname $host off 1
	./dlipower/dlipower.py --hostname $host status 1
        echo -n "Powering ON: "
        ./dlipower/dlipower.py --hostname $host on 1
        ./dlipower/dlipower.py --hostname $host status 1	
        echo -n "Powering OFF: "
        ./dlipower/dlipower.py --hostname $host off 1
        ./dlipower/dlipower.py --hostname $host status 1
done
