#!/bin/bash
# Copyright (c) 2009-2015, Dwight Hubbard
# Copyrights licensed under the New BSD License
# See the accompanying LICENSE.txt file for terms.


# This script must be run in the application root directory
function header {
  python2 -c "s=\"$1\";print \"--\",s,\"-\"*(78-len(s))"
}

function status_message {
  echo "    $1"
}

python3.6 -m venv --clear smoketest
source smoketest/bin/activate
smoketest/bin/pip install --no-cache-dir -U .

for host in `grep -v ^# test/test_host_list`
do
	header "Testing $host"
	status_message "Running Status:"
	dlipower --hostname $host --password "4321" |sed "s/^/    /g"
	echo
	status_message "Testing power management commands, each line should show the same command on both sides of the : character"
	status_message "Forcing power to OFF: `dlipower --hostname $host off 1` `dlipower --hostname $host status 1`"
        status_message "Powering ON: `dlipower --hostname $host on 1` `dlipower --hostname $host status 1`"
        status_message "Powering OFF: `dlipower --hostname $host off 1` `dlipower --hostname $host status 1`"
        echo
        status_message "Testing configuration commands, each line should show the same result on both sides of the : character"
        status_message "Setting port name to PYTHON_TEST `dlipower --hostname $host set_outlet_name 1 PYTHON_TEST` : `dlipower --hostname $host get_outlet_name 1`"
        echo
done

deactivate
rm -rf smoketest
